version: 0.2

env:
  variables:
    GRADLE_USER_HOME: /tmp/gradle-user
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
run-as: codebuild-user
phases:
  install:
    run-as: root
    commands:
      - apt-get update && apt-get install -y openjdk-8-jdk wget
      - apt-get update && apt-get install -y openjdk-11-jdk
      #- apt-get update && apt list | grep openjdk
      #- apt-get update && apt-get install -y openjdk-14-jdk
      - apt-get update && apt-get install -y openjdk-17-jdk
      - apt-get update && wget https://download.java.net/java/GA/jdk14.0.2/205943a0976c4ed48cb16f1043c5c647/12/GPL/openjdk-14.0.2_linux-x64_bin.tar.gz
      - tar xvf openjdk-14.0.2_linux-x64_bin.tar.gz
      - mv jdk-14.0.2 /usr/lib/jvm
      - ls /usr/lib/jvm/
      - export JAVA_HOME=/usr/lib/jvm/jdk-14.0.2/
      - export JAVA8_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
      - export JAVA14_HOME=/usr/lib/jvm/jdk-14.0.2/
      - export JAVA17_HOME=/usr/lib/jvm/java-17-openjdk-amd64/bin/java
      - export JAVA11_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
      # - chown -R codebuild-user:codebuild-user ~/
      # - chmod -R 777 /home/codebuild-user/.gradle
      # - chown -R codebuild-user:codebuild-user /home/codebuild-user/
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    #runtime-versions:
     # java: corretto11
  # pre_build:
  #   run-as: codebuild-user
  #   commands:
  #     - ls -la
  #     # - chmod +x ~
  #     - mkdir -p /tmp/gradle-user/.java/.systemPrefs
  #     - mkdir /tmp/gradle-user/.java/.userPrefs
  #     - chown -R codebuild-user:codebuild-user /tmp/gradle-user/.java
  #     - chmod -R 755 /tmp/gradle-user/.java
  #     - echo "-Djava.util.prefs.systemRoot=/tmp/gradle-user/.java -Djava.util.prefs.userRoot=/tmp/gradle-user/.java/.userPrefs"
  #     - export JAVA_OPTS="-Djava.util.prefs.systemRoot=/tmp/gradle-user/.java -Djava.util.prefs.userRoot=/tmp/gradle-user/.java/.userPrefs"
  build:
    run-as: codebuild-user
    commands:
      - printenv
      # - chown -R codebuild-user:codebuild-user /home/codebuild-user/
      #- ./gradlew precommit
      - ./gradlew check --no-daemon --no-scan
      # name: version
      # name: version
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  #build:
    #commands:
      #./gradlew check --parallel
      # - command
      # - command
  #post_build:
    #commands:
      # - command
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
